[package]
name = "litesvm"
description = "A fast and lightweight Solana VM simulator for testing solana programs"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"
repository = "https://github.com/LiteSVM/litesvm"
readme = "README.md"

[dependencies]
itertools = "0.12"
thiserror = "1.0"
solana-program = "2.0.1"
solana-program-runtime = "2.0.1"
solana-bpf-loader-program = "2.0.1"
solana-sdk = "2.0.1"
solana-system-program = "2.0.1"
solana-compute-budget-program = "2.0.1"
solana-loader-v4-program = "2.0.1"
bincode = "1.3"
indexmap = "2.2.6"
solana-address-lookup-table-program = "2.0.1"
log = "0.4.21"
solana-vote-program = "2.0.1"
solana-stake-program = "2.0.1"
solana-compute-budget = "2.0.1"
solana-config-program = "2.0.1"
solana-svm = "2.0.1"

[dev-dependencies]
spl-token = "3.5.0"
solana-program-test = "2.0.1"
criterion = "0.5"
tokio = "1.35"
test-log = "0.2.15"
solana-config-program = "2.0.1"
serde = "1.0.197"

[features]
internal-test = []

[[bench]]
name = "banks_client_comparison"
required-features = ["internal-test"]
harness = false

[[bench]]
name = "simple_bench"
harness = false

[[bench]]
name = "max_perf"
harness = false

[profile.bench]
debug = true

[profile.release]
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
